# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
Email.create(object:"Coucou",body:"Comment ça va ?", read: false)
Email.create(object:"Salut",body:"Comment ça va aujourd'hui", read: false)
